name: Deploy Strapi and Start Develop

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-and-start:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 instance and deploy Strapi
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          port: ${{ secrets.EC2_SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Attempting SSH connection..."
            cd /home/ubuntu/strapi/examples  # Adjust path to your examples directory
            echo "Changed directory to examples directory."
            cd strapi
            echo "Changed directory to strapi directory."
            yarn install
            echo "Installed dependencies for Strapi."
            cd ../getstarted
            echo "Changed directory to getstarted directory."
            yarn develop
            echo "Started Strapi development server in getstarted directory."
