name: Start Strapi Develop

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  start-develop:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 instance and start Strapi develop
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          port: ${{ secrets.EC2_SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Attempting SSH connection..."
            cd /home/ubuntu/strapi/examples/getstarted  # Adjust path to your Strapi project's getstarted directory
            echo "Changed directory to getstarted directory."
            yarn develop
            echo "Started Strapi develop."
