  name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Yarn
        run: npm install -g yarn

      - name: Clear Yarn cache
        run: yarn cache clean

      - name: Update dependencies
        run: |
          npm install -g npm-check-updates
          ncu -u
          rm yarn.lock

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile || { echo "Installation with --frozen-lockfile failed, retrying with --check-files..." && yarn install --check-files; }

      - name: Build Strapi (if necessary)
        run: yarn build

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/strapi/examples/getstarted  # Navigate to your Strapi project directory
            git pull origin main                      # Pull latest changes from your repository
            yarn install --frozen-lockfile            # Install dependencies (enforcing lockfile consistency)
            pm2 restart strapi                        # Restart Strapi using PM2
