name: SSH Login and Start Strapi Develop Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  start-develop:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 instance and start Strapi develop
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.EC2_SSH_PORT }}
          script: |
            cd /home/ubuntu/strapi
            yarn install
            yarn develop
