name: SSH Login and Start Strapi Develop Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  start-develop:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 instance and start Strapi develop
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          port: ${{ secrets.EC2_SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "Attempting SSH connection..."
            cd /home/ubuntu/strapi/strapi-task  # Adjust path to your Strapi project
            echo "Changed directory to Strapi project."
            yarn install
            echo "Installed dependencies."
            yarn develop
            echo "Started Strapi develop."

      # Add more steps or debugging commands as needed
