name: Deploy Strapi to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: SSH into EC2 instance and start Strapi develop
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          port: ${{ secrets.EC2_SSH_PORT }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH into EC2 instance and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@13.127.147.131 << 'EOF'
            git pull origin main
            cd /home/ubuntu/strapi/examples/getstarted
            yarn install --frozen-lockfile
            yarn build
            pm2 stop all
            pm2 start ecosystem.config.js
          EOF
