name: Deploy Strapi API to EC2

on:
  push:
    branches:
      - main  # Adjust branch name as needed
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Use Node.js 18.x
      # - name: Use Node.js 18.x
      #   uses: actions/setup-node@v2
      #   with:
      #     node-version: '18.x'
      #     registry-url: 'https://registry.npmjs.org/'
      #     cache: 'yarn'

      # # Install dependencies using Yarn
      # - name: Install dependencies
      #   run: yarn install

      # Transfer files to EC2 instance using SCP
      # - name: Transfer files to EC2 instance
      #   uses: appleboy/scp-action@master
      #   with:
      #     host: ${{ secrets.EC2_HOST }}
      #     username: ${{ secrets.EC2_USERNAME }}
      #     key: ${{ secrets.EC2_PRIVATE_KEY }}
      #     source: './'  # Adjust path to your Strapi project directory
      #     target: '/home/ubuntu/strapi/examples/getstarted'  # Adjust remote path as needed

      # SSH into EC2 instance and execute deployment commands
      - name: SSH into EC2 instance and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            cd /home/ubuntu/strapi/examples/getstarted
            yarn install  # Reinstall dependencies (optional)
            yarn develop &  # Start Strapi development server
            sleep 10  # Wait for the server to start
